#!/usr/bin/env bash
#serving HTML pages, lets install one
apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Holberton School for the win!" > /var/www/html/index.html
/etc/init.d/nginx start
