#!/usr/bin/env bash
# displays the time for 12 hours and 59 minutes
H=0
M=1
while [ $H -lt 13 ]
do
    echo "Hour: $H"
    while [ $M -lt 60 ]
    do
        echo "$M"
	M=$((M+1))
    done
    H=$((H+1))
    M=1
done
